### ISSUE TITLE
Model FK is not updated dynamically

### ISSUE THREAD

**Issue by ernsheong** [tommikaikkonen/redux-orm#243] opened 2019-02-04 00:14 UTC
Hi there, 

I have a Card model, with associated Track/Stages.

Card loads, model gets created. A split second later, track/stages arrive.

However, `card.track` returns null even though track is in redux-orm DB

![image](https://user-images.githubusercontent.com/1343284/52184954-ce98e000-2854-11e9-89e9-e79bbf7c4912.png)

What is the way to address this so that `card.track` does not return null?

Version: 0.12.2

**Comment by ernsheong** [comment] 2019-02-07 07:44
Perhaps this is more of a redux selector dependency issue.

**Comment by kirbydcool** [comment] 2019-02-09 00:17
I ran into this issue as well.
It looks like an issue with the orm state memoize function, which uses the cached value if all of the tables your selector accessed are equal to the previous call's value. I'd guess that redux orm is not accessing the related tables if the related id doesn't exist, so it's not checking those tables when figuring out whether or not to use the cached value on subsequent calls, thus using the cached value.

A way to work around this for know would be to manually access the related tables in your selector.
```
const selectCardById = createSelector(
  orm,
  ...
  (session, id) => {
    session.Track.count() . // trick the selector into looking at the Track table
    session.Stage.count() .// trick the selector into looking at the Stage table
    return session.Card.withId(id)
  }
```
Note this won't help for related records of the related records.

**Comment by haveyaseen** [comment] 2019-02-12 16:15
Hey guys, thanks for reporting here. Unfortunately I'm unable to reproduce the issue, even after writing a test to confirm the reported error:

https://github.com/tommikaikkonen/redux-orm/blob/4267303bf56cab58e14742bbe750b0a40315d69e/src/test/integration/redux.js#L232-L302

Would one of you like to create a minimal example on [CodeSandbox](https://codesandbox.io) or directly as a failing test?

**Comment by kirbydcool** [comment] 2019-02-12 21:40
I'll take a stab at writing a failing test when I get some free time.

**Comment by kirbydcool** [comment] 2019-02-13 03:56
@haveyaseen I opened a pr that demonstrates the issue in a test. https://github.com/tommikaikkonen/redux-orm/pull/245

**Comment by haveyaseen** [comment] 2019-02-13 11:15
@kirbydcool Thank you. This demonstrates why you should have your selectors return references and not model instances (see also https://github.com/tommikaikkonen/redux-orm/issues/218#issuecomment-402448424 and #239). Although technically you could cause the selector to re-run by accessing the models' relationships, you are way better off by creating a second selector for your relationships.

For this reason I'm closing this issue and the corresponding PR.

**Closed by haveyaseen** 2019-02-13 11:15 UTC

**Comment by kirbydcool** [comment] 2019-02-13 18:47
Thanks for taking a look!
I was not aware that returning ref arrays were considered best practice. I think it's unintuitive enough to warrant a section in the doc that calls this out as a best practice and gives some context to the reasoning and limitations of this approach.

You miss out on having convenient access to relationships and any model instance methods you've defined. It also makes it clunkier to compose selectors, something like:
```
    const moviesByRating = createSelector(
        orm,
        [
            state => state.db,
            (db, rating) => rating
        ],
        (session, rating) => session.Movie.filter({ rating }).toModelArray()
    )

    const publishersWithMovieByRating = createSelector(
        orm,
        [
            state => state.db,
            moviesByRating,
        ],
        (session, movies) => (
            Array.from(
                movies.reduce(
                    (publishers, movie) => publishers.add(movie.publisher),
                    new Set()
                )
            )
        )
    )
```
