### ISSUE TITLE
Problem of getting many-to-many relations 

### ISSUE THREAD

**Issue by Starodubenko** [tommikaikkonen/redux-orm#247] opened 2019-02-28 20:16 UTC
Hello!
I have tried to use redux-orm in my pet project and got an issue.

The issue is about getting **many-to-many** refs in Model

**First of all - util function**
```javascript
export type ReduxOrmModelReducer<P, ORMState extends ORMCommonState> = (action: Action<P>, modelClass: typeof Model, session: SessionWithModels<ORMState> )=> any

export function createReduxOrmModelReducer<HandlersMap, P, ORMState extends ORMCommonState>
                                          (map: HandlersMap): ReduxOrmModelReducer<P, ORMState> {
    return (action: Action<P>, model: any, session: SessionWithModels<ORMState>) => {
        const handler = map[action.type];
        handler && handler(action, model, session);
    }
}
```

My Models:
**Author**
```javascript
export class AuthorSchema extends Model<Author> {}
AuthorSchema.modelName = 'Author';
AuthorSchema.reducer = authorReducer;
```
**Author reducer**
```javascript
export interface IAuthorActionHandlers {
    [BookCreateActionType]: ReduxOrmModelReducer<Book, AppEntitiesState>;
    [AuthorCreateActionType]: ReduxOrmModelReducer<Author, AppEntitiesState>;
    [AuthorUpdateActionType]: ReduxOrmModelReducer<Author, AppEntitiesState>;
    [AuthorDeleteActionType]: ReduxOrmModelReducer<string, AppEntitiesState>;
}

export const authorActionsMap: IAuthorActionHandlers = {
    [BookCreateActionType]: (action, model, session) => {
        action.payload.authors.forEach(author => {
            model.create(author);
        });
    },
    [AuthorCreateActionType]: (action, model, session) => {
        model.create(action.payload);
    },
    [AuthorUpdateActionType]: (action, model, session) => {
        model.withId(action.payload.id).update(action.payload)
    },
    [AuthorDeleteActionType]: (action, model, session) => {
        model.withId(action.payload).delete();
    }
};

export const authorReducer = createReduxOrmModelReducer<IAuthorActionHandlers, Author, AppEntitiesState>(authorActionsMap);
```

**Publisher and Book schemas**
```javascript
export class PublisherSchema extends Model<Publisher> {}
PublisherSchema.modelName = 'Publisher';

export class BookSchema extends Model<Book> {
    static get fields() {
        return {
            publisher: oneToOne('Publisher'),
            authors: many('Author', 'books')
        }
    }
}
BookSchema.modelName = NS;
BookSchema.reducer = bookReducer;
```

**Book reducer**
```javascript
export interface IBookActionHandlers {
    [BookCreateActionType]: ReduxOrmModelReducer<Book, AppEntitiesState>;
    [BookUpdateActionType]: ReduxOrmModelReducer<Book, AppEntitiesState>;
    [BookDeleteActionType]: ReduxOrmModelReducer<string, AppEntitiesState>;
}

export const bookActionsMap: IBookActionHandlers = {
    [BookCreateActionType]: (action, model, session) => {
        const authorIds = action.payload.authors.map(author => author.id);
        const book = Object.assign({}, action.payload, { authors: authorIds });
        model.create(book);
    },
    [BookUpdateActionType]: (action, model, session) => {
        model.withId(action.payload.id).update(action.payload)
    },
    [BookDeleteActionType]: (action, model, session) => {
        model.withId(action.payload).delete();
    }
};

export const bookReducer = createReduxOrmModelReducer<IBookActionHandlers, Book, AppEntitiesState>(bookActionsMap);
```

Selector that I used to get **many-to-many** authors in the **Book** Model
 ```javascript
export const bookListSelector = (appState: AppState) => createSelector(
    appStateOrm,
    dbStateSelector,
    session => {
        return session.Book.all().toModelArray().map(book => {
            const obj = book.ref;

            return Object.assign({}, obj, {
                authors: book.authors.map(author => author.name),
            });
        });
    }
)(appState.entities);
```

Have no idea what went wrong, if anyone sees a mistake in this code pls tell me.

**Comment by haveyaseen** [comment] 2019-03-19 14:36
Hard to tell. The selector looks strange to me, this would probably be closer to the docs:
```javascript
export const bookListSelector = createSelector(
   appStateOrm,
   dbStateSelector,
   session => {
       return session.Book.all().toModelArray().map(book => {
           const obj = book.ref;

           return Object.assign({}, obj, {
               authors: book.authors.map(author => author.name),
           });
       });
   }
);
```
What's going wrong exactly?

**Comment by Starodubenko** [comment] 2019-03-19 17:28
I couldn't get related values i.e. **authors**

I guess I found out where the problem was ... 
The problem was in separated reducer handlers

`
[BookCreateActionType]: (action, model, session) => {
        action.payload.authors.forEach(author => {
            model.create(author);
        });
    },
`
and 
`
[BookCreateActionType]: (action, model, session) => {
        const authorIds = action.payload.authors.map(author => author.id);
        const book = Object.assign({}, action.payload, { authors: authorIds });
        model.create(book);
    },
`

The firs of first 
`
model.create(author);
`
must be
and then
`
model.create(book);
`
in the same handler, In such case it works.

because, under the hood, relations gets created only if related values exist, in this case - **authors**

**Comment by haveyaseen** [comment] 2019-03-26 12:22
Glad you got this resolved. To be clear, yes you need to create both the `Book` and `Author` models yourself. Author instances won't be created when you pass in a book that has an `authors` property, that is Redux-ORM doesn't do normalization of inputs for you.

Still not sure why it didn't work for you (see https://codesandbox.io/s/llp1mw4lrz for a working example where I tried to reproduce the issue). But since you said it's resolved I'm closing this anyways.

**Closed by haveyaseen** 2019-03-26 12:22 UTC
Labels: type: Question
