### ISSUE TITLE
v0.9.1 -> v0.9.4 introduces error while creating records

### ISSUE THREAD

**Issue by orecus** [tommikaikkonen/redux-orm#193] opened 2018-03-27 13:57 UTC
I'm currently revisiting an older project, where we are using v0.9.1 of redux-orm, while updating to the latest version, it seems that there are some breaking changes (or fixes) that i've yet to identify what they are and what changes would be needed.

The code below all works exactly as is, in v0.9.1 of redux-orm.

Error:
```js
Uncaught (in promise) TypeError: values.map is not a function
    at Model.js:232
    at Array.forEach (<anonymous>)
    at SessionBoundModel._refreshMany2Many (Model.js:227)
    at Function.create (Model.js:340)
    at role.js:26
    at Array.forEach (<anonymous>)
    at Function.reducer (role.js:23)
    at redux.js:18
    at Array.forEach (<anonymous>)
    at defaultUpdater (redux.js:15)
```

role.js;
```js
import { Model, many, fk } from 'redux-orm';

import { ADMIN_CREATE_ROLE_SUCCESS, LOAD_ROLES, ADMIN_UPDATE_ROLE_SUCCESS } from '../components/admin/actions';

export class Role extends Model {
  static reducer (action, Role, session) {
    const { payload, type } = action;
    const Department = session.Department;

    switch (type) {
      case ADMIN_CREATE_ROLE_SUCCESS:
        const role = payload.data;
        Role.create(role);

        if (role.DepartmentId != null) {
          Department.withId(role.DepartmentId).roles.add(role.id);
        }

        break;
      case LOAD_ROLES:
        const roles = action.roles;

        roles.forEach(role => {
          console.log('role', role);

          Role.create(role); //Error here

          if (role.DepartmentId != null) { Department.withId(role.DepartmentId).roles.add(role.id); }
          if (role.RoleId != null) { Role.withId(role.id).RoleId = role.RoleId; }
        });

        break;
      case ADMIN_UPDATE_ROLE_SUCCESS:
        const originalRoleObject = Role.withId(payload.data.id).ref;

        if (originalRoleObject.DepartmentId != payload.data.DepartmentId) {
          Department.withId(originalRoleObject.DepartmentId).roles.remove(originalRoleObject.id);
          Department.withId(payload.data.DepartmentId).roles.add(payload.data.id);
        }

        console.log('Payload', payload.data);
        console.log('originalRoleObject', originalRoleObject);
        Role.withId(payload.data.id).update(payload.data);

        break;
    }
  }
}

Role.modelName = 'Role';
Role.options = { idAttribute: 'id' };
Role.fields = {
  RoleId: fk('Role', 'children'),
  employees: many('User', 'RoleId'),
  access: many('AccessDefinition', 'RoleId')
};
```

sample role;
```js
{
DepartmentId: 1,
RoleId: null,
createdAt: "2018-03-27T12:03:12.321Z",
createdBy: "firstname.lastname",
deletedAt: null,
id: 1,
isDeleted: false,
isManager: true,
modifiedBy: null,
name: "CEO",
updatedAt: "2018-03-27T12:03:12.321Z",
}
```

Any ideas?

**Comment by markerikson** [comment] 2018-03-27 15:18
Not sure, but based on the error, it's crashing here:

https://github.com/tommikaikkonen/redux-orm/blob/deb0ca5a2afcd0d6e9ca2b5201897e9f953ae1a3/src/Model.js#L199

**Comment by orecus** [comment] 2018-04-03 13:08
@markerikson I've tried debugging this, pulling my hair here. I just can't figure out if I'm doing something wrong in the models, if the api was changed between .9.1 and .9.4 that could be causing this, or if something else is missing.

**Comment by haveyaseen** [comment] 2018-06-13 10:04
Hi @orecus, thank you for reporting this. The error was likely introduced with 7766cc6, but it's still a dupe of #101.
In your case it may be that `RoleId` being `null` is the culprit. Also, your `many()` relations should look something like this:
```diff
Role.fields = {
  RoleId: fk('Role', 'children'),
-  employees: many('User', 'RoleId'),
-  access: many('AccessDefinition', 'RoleId')
+  employees: many({
+    to: 'User',
+    relatedName: 'roles',
+    throughFields: ['RoleId', 'id'],
+  }),
+  access: many({
+    to: 'AccessDefinition',
+    relatedName: 'roles',
+    throughFields: ['RoleId', 'id'],
+  }),
};
```
Please try the above changes with v0.10.2.

**Closed by haveyaseen** 2018-06-13 10:04 UTC
Labels: type: Bug

**Comment by orecus** [comment] 2018-07-10 09:16
@haveyaseen Sorry for the late reply, was on vacation. :)

I'm not sure if this is the best way to do it, but the application loads the database models in different steps and for each step it relates the record to previously loaded model's data and then i load them in order of how they are needed. So employees and access upon inital load of the Roles, are all null/undefined.

```js
      case LOAD_USERS:
        const users = action.users;

        users.forEach(user => User.create(user));

        users.forEach(function (user) {
          if (user.RoleId != null) {
            User.withId(user.id).role = user.RoleId;
            User.withId(user.id).manager = user.ManagerId;
            Department.withId(user.DepartmentId).employees.add(user.id);
            Role.withId(user.RoleId).employees.add(user.id);
          }
        });
        break;
```

With the latest version of redux-orm (thanks for the new updates! :) ) the error is changed to this with your modifications above;

```js
Uncaught TypeError: Cannot read property 'isForeignKeyTo' of undefined
    at ManyToMany.getThroughFields (fields.js:276)
    at ManyToMany.createForwardsDescriptor (fields.js:384)
    at DefaultFieldInstaller.installForwardsDescriptor (fields.js:130)
    at DefaultFieldInstaller.run (fields.js:58)
    at installField (fields.js:37)
    at ORM.js:174
    at _createBaseFor.js:17
    at baseForOwn (_baseForOwn.js:13)
    at forOwn (forOwn.js:33)
    at ORM.js:172
```

and without the modifications

```js
Model.js:224 Uncaught (in promise) TypeError: Failed to resolve many-to-many relationship: Role[DepartmentId] must be an array (passed: 1)
    at Model.js:224
    at Array.forEach (<anonymous>)
    at SessionBoundModel._refreshMany2Many (Model.js:218)
    at Function.create (Model.js:336)
    at role.js:28
    at Array.forEach (<anonymous>)
    at Function.reducer (role.js:23)
    at redux.js:17
    at Array.forEach (<anonymous>)
    at defaultUpdater (redux.js:14)
```

The code base is fairly old, and not the best written so I'm considering just rewriting it all anyway if there is no "quick" fix for this, as most of it is quite outdated.

**Comment by haveyaseen** [comment] 2018-07-10 10:47
Hi @orecus, how come department objects have a `roles` field? There seems to be a superfluous many-to-many relationship between `Role` and `Department`. Please post your `Department.fields` code. If you refer to a `DepartmentId` in your role objects, it should probably just be a foreign key field:
```javascript
Role.fields = {
  DepartmentId: fk('Department', 'roles'),
  /**
   * now possible like this as well (with a custom accessor defined by 'as')
   * this way role.DepartmentId will stay a number and the department itself
   * can be accessed through role.department
   */
  DepartmentId: fk({
    to: 'Department',
    as: 'department',
    relatedName: 'roles',
  }),
  RoleId: fk('Role', 'children'),
  // or
  RoleId: fk({
    to: 'Role',
    as: 'parent',
    relatedName: 'children',
  }),
  employees: many('User', 'roles'),
  access: many('AccessDefinition', 'roles'),
};
```
In fact, it seems like you are managing foreign key relationships by yourself. **Redux-ORM can do that for you.** There is absolutely no need to manage the `department.roles` backwards field. It is automatically updated if you define a foreign key as per the above!

I was wrong advising you to set `throughFields` by yourself. This property relates to the through model and should not be set unless you are using a custom through model (which is unnecessary). That is likely why it errors on `isForeignKey` being called on `undefined` -- the two supplied `throughFields` do not exist on the through model as they are named differently by default.

As regards the codebase being stale, actually I have been refactoring it and now it is much easier to understand as well as pretty flexible and much more elegant than before. Also currently working on self-referencing many relationships, but they are unrelated to your issue.

**Comment by haveyaseen** [comment] 2018-07-10 10:54
You may be confusing `many` and `fk` fields altogether. `many` is strictly for many-to-many relationships and has nothing to do with foreign keys. While I don't know exactly what your goals are with `employees` and `access`, you may be better served removing those two fields and defining the relationship towards `Role` with a `RoleId: fk('Role', 'employees')` and `RoleId: fk('Role', 'access')` field in `User` and `AccessDefinition` respectively.


See #191 for more information.

**Comment by orecus** [comment] 2018-07-10 11:20
@haveyaseen Thanks for your clear and thorough answer! When i mentioned codebase being stale, I was talking about my applications code base, not redux-orm's. :)

A bit of background may be in order of what this i used for; it's an internal access management for employee access. Where access is granted by an employee having a specific role, tied to their department. Access is related to the role, not the user directly. What i intended of doing was that a Role can belong to many users, have many accessDefinition's, belong to a single department and having a parent role.

I see what you are saying, I'm probably trying to manage the foreign key's without realizing at the time this was written. I think you are on point that i may have confused fk with many, when this was written i tried to translate the backend database structure if i'm not misstaken straight to redux-orm. 

I think the whole application is need of a bigger overhaul, and probably rethink the implementation in some areas. It's clear i did not know what i was doing, but it kind-of worked at the time. ;)
