### ISSUE TITLE
Memoize on selectors, accessing models outside of session

### ISSUE THREAD

**Issue by Aryk** [tommikaikkonen/redux-orm#71] opened 2016-12-21 21:23 UTC
It seems like if you use the createSelectors to get objects, you have to do all the accessing inside the selector block. If you do it afterward you get the object from the selector, it won't get marked as 'accessed'. Was this the desired behavior.

This hides some issues where you update relationships on an object, and then go back to get that object, and find the relationships haven't changed.

I supposed you could put in the selector Model.markAccessed so that it knows to invalidate based on other models, but seems very verbose. Is it possible to somehow specify on createSelectors, like specify an array of models that will be accessed on the object? If it exists, I'm sorry, I didn't catch it in the code.

You could do all the accessing in the selector, but it seems excessive because the beauty of redux-orm is that you can access the relationships off of the model object outside of the selector.

**Comment by tommikaikkonen** [comment] 2016-12-22 01:39
It is definitely suboptimal. Like you said, you can encounter some gnarly unexpected behavior there that's hard to debug.

You can reduce memoization problems by composing query functions operating on sessions/models/querysets without any `createSelector` facilities, and then wrap the final selector with `createSelector`. This ensures that the whole selector will be run in sight of Redux-ORM specific `memoize`, recording accessed models correctly.

```javascript
function _selectBooks(session) {
    return session.Books.all();
}

function _selectFirstBook(session) {
    return _selectBooks(session).first();
}

const selectFirstBook = createReducer(orm, state => state.orm, _selectFirstBook);
```

`reselect` works great for tree-shaped data, where you go from state to substate. With related data, you need jump back and forth between states, substates and sibling states, so memoization isn't as straightforward and concepts in `reselect` documentation might not apply well here.

The correct solution is probably to build more robust query invalidation to Redux-ORM, but I haven't given that any thought since the simple memoization worked well enough for my needs.

Manually annotating which models are accessed, like you said, would work but I don't feel it's the long term solution; developers will forget to list some models and it'll be hard to trace those bugs. Feel free to submit a PR for manually annotating those Models if you need that capability in your project.

**Comment by Aryk** [comment] 2016-12-22 10:40
Here was my solution:

```js
import { dbStoreKeyHelper } from './reducers';
import { orm } from '../orm';
import { createSelector } from 'redux-orm';
import { last, isPlainObject, castArray } from 'lodash';

/**
 * Convenience wrapper for creating a memoized selector. Deep down it uses the memorizer here:
 * https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/memoize.js#L69.
 *
 * Usage:
 *
 *      createOrmSelector(select1, select2, (session, select1Result, select2Result) => (
 *         session.Book.count + select1Result + select2Result
 *      ))
 */
const createOrmSelector = (...args) => {
  return (store, ...selectorArgs) => {
    const lastIndex = args.length - 1;
    args[lastIndex] = addMarkAccessedFunctionality(args[lastIndex], selectorArgs);
    const selector = createSelector(orm, dbStoreKeyHelper.getStateSelector(), ...args);
    return selector(store, ...selectorArgs);
  };
};

/**
 * Adds functionality to specify which models will be access so that it will know when to bust the cache.
 */
const addMarkAccessedFunctionality = (selectorFunc, selectorArgs) => {
  if (isPlainObject(last(selectorArgs))) {
    const options: {markAccessed: string | string[]} = selectorArgs.pop();

    return (session, ...rest) => {
      castArray(options.markAccessed).forEach(modelName => session.markAccessed(modelName));
      return selectorFunc(session, ...rest);
    };
  } else {
    return selectorFunc;
  }
};

export { createOrmSelector }
```

So then we have:

```js
@connect(
  state => {
    const book = bookSelectors.first(state, {markAccessed: ['Page', 'PageItems']});
 }
)
```

**Comment by Aryk** [comment] 2017-01-07 15:38
Previous solution was not memoizing due to recreating memoizing function each time. Here is the new version:

```js
import { orm, dbStoreKeyHelper } from '../utils/orm';
import { createSelector } from 'redux-orm';
import { last, isPlainObject, castArray } from 'lodash';

type OrmSelectorOptionsType = {markAccessed?: string | string[]};
/**
 * Convenience wrapper for creating a memoized selector. Deep down it uses the memorizer here:
 * https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/memoize.js#L69.
 * 
 * It also allows for listening to other associations for changes in the event you make changes to those and retrieve
 * only their top level parent.
 *
 * Usage:
 *
 *      createOrmSelector(select1, select2, ((session, select1Result, select2Result) => (
 *         session.Book.count + select1Result + select2Result
 *      )), {markAccessed: ['Book', 'Page']})
 */
const createOrmSelector = (...args) =>
  createSelector(orm, dbStoreKeyHelper.getStateSelector(), ...addMarkAccessedFunctionality(args));

/**
 * Adds functionality to specify which models will be access so that it will know when to bust the cache.
 */
const addMarkAccessedFunctionality = (args) => {
  if (isPlainObject(last(args))) {
    const options: OrmSelectorOptionsType = <OrmSelectorOptionsType> args.pop();
    if (options.markAccessed) {
      const lastIndex = args.length - 1;
      const selectorFunc = args[lastIndex];
      args[lastIndex] = (session, ...rest) => {
        castArray(options.markAccessed).forEach(modelName => session.markAccessed(modelName));
        return selectorFunc(session, ...rest);
      };
    }
  }
  return args;
};

export { createOrmSelector, OrmSelectorOptionsType }
```

**Comment by Aryk** [comment] 2017-01-07 15:45
> Manually annotating which models are accessed, like you said, would work but I don't feel it's the long term solution; developers will forget to list some models and it'll be hard to trace those bugs. Feel free to submit a PR for manually annotating those Models if you need that capability in your project.

I think it's actually not a bad idea to manually annotate (per my solution above). When you start having too much magic, it makes code harder to figure out. One of the benefits of Redux ORM is it's relatively small. I spent *alot* of time in the past figuring out the internals of ActiveRecord and *even* then you have things like `include => ['assoc1', 'assoc2']` when querying objects to remove additional hits to the database. I guess what I'm saying is its not asking for much to say which models will be accessed from your selector upfront and corollary to it "probably" involves a lot more logic and complexity as you need to keep state. Even if you do that, you will have some solution where they update a deep child and the selector doesn't work and then they will wonder why their selector isn't memoizing...

**Comment by adamborowski** [comment] 2017-02-01 17:08
It seems be a good practise - to never leak redux-orm specific objects from selectors.
Bad example:
`
const selectedUser = createSelector(..., session=>session.Scenario.all().toModelArray())
// usage:
const myUser = selectedUser(state);
const myFirstBook = myUser.books.all().toRefArray()[0];
`

Good exmaple:
`
const selectedUser = createSelector(..., session=>session.Scenario.all().toModelArray().map(model=>({...model.ref, books: model.books.all().toRefArray()})))
// usage:
const myUser = selectedUser(state);
const myFirstBook = myUser.books.all().toRefArray()[0];
`

Am I right?

**Comment by Aryk** [comment] 2017-02-01 19:17
Yeah, it's not a bad practice, but I don't feel like it should be the only way. What if you needed a method off the Book's model? Then you have to call those methods and re-add them to that hash you are creating in selectedUser.

What if you want to resuse selected user, but you need different methods off the Book model? Now you have to add those or create another selectedUser method for that specific use case (or make it into a factory).

This will result in much hard to reason about code. In my case, all you do is throw in {markAccessed: ['books']} and then move on with your life and use functions you wrote in your models with a much higher probability of being able to reuse the selector.

**Comment by jordan-enev** [comment] 2017-08-08 12:29
@Aryk I'm having the same case as yours.

Accessing models methods / references dynamically looks fine for me. Otherwise we have to create very specific selectors and the boilerplate would be more.

However, I'm trying your solution and currently it works fine. Thank you so much for the contribution.

I make it ES6 compatible:

```javascript
import orm from '../redux/orm'
import { createSelector } from 'redux-orm'
import { last, isPlainObject, castArray } from 'lodash'

/**
 * Convenience wrapper for creating a memoized selector. Deep down it uses the memorizer here:
 * https://github.com/tommikaikkonen/redux-orm/blob/feature/eager_updates/src/memoize.js#L69.
 *
 * It also allows for listening to other associations for changes in the event you make changes to those and retrieve
 * only their top level parent.
 *
 * Usage:
 *
 *      createOrmSelector(select1, select2, ((session, select1Result, select2Result) => (
 *         session.Book.count + select1Result + select2Result
 *      )), {markAccessed: ['Book', 'Page']})
 *
 * For more details:
 * @url - https://github.com/tommikaikkonen/redux-orm/issues/71#issuecomment-271090516
 */
const createORMSelector = (...args) =>
  createSelector(orm, state => state.orm, ...addMarkAccessedFunctionality(args))

/**
 * Adds functionality to specify which models will be access so that it will know when to bust the cache.
 */
const addMarkAccessedFunctionality = (args) => {
  if (isPlainObject(last(args))) {
    const options = args.pop()
    if (options.markAccessed) {
      const lastIndex = args.length - 1
      const selectorFunc = args[lastIndex]
      args[lastIndex] = (session, ...rest) => {
        castArray(options.markAccessed).forEach(modelName => session.markAccessed(modelName))
        return selectorFunc(session, ...rest)
      }
    }
  }
  return args
}

export { createORMSelector }

```

**Comment by Aryk** [comment] 2017-08-08 16:08
Hey @jordan-enev thanks for improving this. I actually held off on using this in my code for two reasons:

1. It's not in the core library. So I'm adding specific code and logic that only I'm aware about.
2. If I don't use it, I simply create specific selectors that call session.markAccessed(Page) or session.markAccessed(PageItem) which doesn't seem "that much worse" although slightly more verbose.

Obviously if I needed to do this (# 2) many times in my code, I would justify going back to my solution, but just wanted to throw it out there. Indirection specific to your app without community support just means devs working on it, have to understand how you are extending libraries only in your code.

Would love for this to actually get into redux-orm, then I would use it for sure even if it was in one spot in my code.

**Comment by markerikson** [comment] 2018-01-07 19:21
Is any of this still relevant with the current version of Redux-ORM?

**Comment by jordan-enev** [comment] 2018-01-08 08:54
I tried the above workflow for a few months and these days I stopped using it and I refactored all the selectors, for the following reasons:

1. Don't expose Models logic down to components (both Containers & Presentations). Keep the complexity in only one layer (the selectors) and keep your components simple. Doing it in that way - only the selectors will know about the ORM and the components will just get the needed data and render it.
2. Having in mind the above reason (a.k.a. specific selectors), the tests of selectors and components will be easier.

Yeah, you have to create more specific selectors, but the above pros will pay you back.

**Comment by markerikson** [comment] 2018-01-12 22:20
Related question to this: right now it seems that the `markAccessed` functionality works at the level of a single `Model` "table".  It would be useful if this could be more granular, down to specific instances.

In particular, someone was asking me the other day about a scenario where a `Page` can have many `Question`s, and there's multiple pages.  An update to any `Question` instance is causing all selectors that access `session.Question` to re-run, when ideally it would only re-run if questions relevant to that page were updated.  Example selector:

```js
return createSelector(orm, selectPresent, selectItemId, (session, id) => {
        const pageModel = session.Page.withId(id);
        const questions = pageModel.questions.toModelArray().map(q => q.id);
        return questions;
    });
```

**Comment by B-Reif** [comment] 2018-01-12 23:31
Reselect proper has this API that allows for customized memoization:
https://github.com/reactjs/reselect#createselectorcreatormemoize-memoizeoptions

In the absence of a more granular selection for models, this functionality would be nice to have. (Can I swap in reselect for redux-orm's selectors?)

**Comment by B-Reif** [comment] 2018-01-22 23:29
I'm considering creating a PR to memoize down to the instance level.

Currently `markAccessed` just pushes table names onto an array. I want to propose changing `accessedModels` to an object that contains table names as keys, with values pointing to the instance ids that have been accessed.

Before:
```
accessedModels: ["Page, "Question"]
```
After:
```
accessedModels: {
    Page: [0, 1],
    Question: [0]
}
```
Does this make sense?

**Comment by Aryk** [comment] 2018-01-22 23:42
Conceptually, that would be awesome....the benefits of memoize goes away a ton if you are doing it on the level of the entire "table", because it forces a refresh on a lot of unrelated instances.

Also, swapping reselect for redux-orm's selectors would also be welcome assuming it wouldn't change other functionality. Understanding the current memoize code was a PITA, but maybe there is a reason there was used a customized memoizer function....i'm not sure.

**Comment by nealoke** [comment] 2018-01-23 11:14
I honestly thought that this was already the case and know now why my application sometimes freezes when performing a large amount of updates on unrelated sibling instances... Any way we could solve this?

**Comment by plandem** [comment] 2018-01-23 17:38
Per instance memoization can bring us to higher memory consumption and also speed degree in some cases. But it's my point of view as developer in general only. 

E.g. (we have 10k records):

Cases:
1) only 1 record changed
2) 5k record changed
3) 10k record changed


so questions are:
a) what the speed degrade
b) what the memory required

**Comment by B-Reif** [comment] 2018-01-23 19:02
We could expose a redux-orm flavor of `createSelectorCreator` so developers can specify their own memoization function. Under the hood, redux-orm already uses reselect's version:

```js
// redux.js
export function createSelector(orm, ...args) {
    if (args.length === 1) {
        return memoize(args[0], eqCheck, orm);
    }

    return createSelectorCreator(memoize, eqCheck, orm)(...args);
}
```

The current implementation of `memoize` maps each accessed table to a validator function:
```js
// memoize.js
Object.keys(session.accessedModels).forEach((modelName) => {
    if (!modelNameToInvalidatorMap.hasOwnProperty(modelName)) {
        modelNameToInvalidatorMap[modelName] = nextState =>
            lastOrmState[modelName] !== nextState[modelName];
    }
});
```

Any implementation of `memoize` can only be as detailed as the info it gets from `session.accessedModels`. I would maintain that `accessedModels` should track at least to the instance level. (Even finer granularity could be possible; we could track which relations or attrs were accessed, but I think that might be overkill?)

From there, we can have a default implementation of `memoize`, and expose `createSelectorCreator` which accepts a custom `memoize` function that receives `session.accessedModels` and compares the states however the developer wants.

**Comment by Aryk** [comment] 2018-01-23 21:04
@plandem 

a) What do you mean by speed degrade? If anything we'll actually get a speed improvement, a significant one. Rerenders and repainting are some of the most expensive operations you can be doing. It is also the one the user will notice via annoying lags.

b) Versus actually have 10k objects already in redux orm, what do you think the additive memory consumption would be to maintain a hash with IDs -> 0/1 to keep track of  "dirty" records? I'm willing to bet that additional memory required is in the single-digit percentages...

To me, not having instance-level invalidation is one of the biggest knocks on redux-orm because it does not play nicely with react-redux's `@connect` function.
 
@B-Reif  - I would vote for still keeping the ability to invalidate the entire model in case you refreshed from your API and just want to refresh everything, but this should be able to live alongside instance level.

I'm a huge fan of making this default level behavior and IMO have not heard convincing arguments for why it is more bad than good....

**Comment by plandem** [comment] 2018-01-23 21:15
@Aryk 
a) previously we checked only modelName for flag, no we are going to check modelName + idList. For sure we will have some speed degrade.
b) memory maybe not so critical here, you are right. Just array of 10k integers (in case of numerical primary key).

Anyway, it depends on implementation. Just need to benchmark before/after and we will see the difference. Maybe related to 'premature optimization' only.

**Comment by B-Reif** [comment] 2018-01-23 21:17
There's a work-in-progress PR at #185, feel free to comment / discuss some of the individual changes over there as well.

**Comment by haveyaseen** [comment] 2018-06-06 21:15
Closing as #185 is merged.

**Closed by haveyaseen** 2018-06-06 21:15 UTC

**Comment by haveyaseen** [comment] 2019-05-11 20:26
Selectors are now composable and accept ID arguments with automatic caching based on re-reselect! Please try out [v0.14.0-rc.0](https://github.com/redux-orm/redux-orm/releases/tag/v0.14.0-rc.0) :slightly_smiling_face:
