### ISSUE TITLE
Creating temporary ORM for testing results in TypeError: "Cannot redefine property"

### ISSUE THREAD

**Issue by AlisterC93** [tommikaikkonen/redux-orm#159] opened 2017-09-12 05:14 UTC
For the sake of testing Models (or more accurately their reducers) I have created a function that creates a Redux Store with only the specified ORM Models in it, to run assertions on it to ensure the correct actions are dispatched and objects are created and saved in the store. This works fine for models without any relations, however when I attempt to test any model that has a relation to another, I get "TypeError: Cannot redefine property X" - X being a property of the model that has the relation to another Model. After thoroughly examining the process, it seems this occurs at the createStore function.
```
import {ORM} from "redux-orm";

function prepareStore(Models) {
    let testORM = new ORM();

    let passMods = Object.values(Models);
    testORM.register(...passMods);

    let ormReducer = createReducer(testORM);
    let reducers  = combineReducers({
        orm: ormReducer,
    })

    let fakeStore = createStore(    // Error appears to occur here
        reducers,
        undefined,
        undefined,
    );
    return fakeStore;
}
```
And an example of test that completes without error appears as
```
import * as Models from "models";

it ("Creates a Test Model", function() {
    let fakeStore = prepareStore({Models.Test});
    let testData = {
        id: 0,
        name: "TEST",
    };

    let testAction = {
        type: Constants.CREATE_TEST,
        payload: testData,
    };
    fakeStore.dispatch(testAction1);

    let ormState = fakeStore.getState().orm;
    expect(ormState.Test.itemsById["0"].id).to.equal(0);
    expect(ormState.Test.itemsById["0"].name).to.deep.equal("TEST");
    expect(ormState.Market.meta.maxId).to.equal(0);
});
```
The curious aspect is in our production environment, all the models are registered at once and there are no errors regarding property redefinition.

**Comment by AlisterC93** [comment] 2017-10-30 03:15
Minimal repository replicating the issue can now be found at
https://github.com/QPSBenchmarking/redux-orm-test

**Comment by haveyaseen** [comment] 2018-06-10 18:28
Thank you @AlisterC93, especially for providing the repository to reproduce the error! I actually managed to fix the error by replacing the following line in **test/test.jsx**:
```diff
- let passMods = Object.values(Models);
+ let passMods = Object.values(Models).map(m => class extends m {});
```
noticing this is most likely a duplicate #156. Because of this, I am also closing this issue. We should fix this within the library!

For anyone who cares, the exact output I got was:
```
ORM Testing example Creates a Test ModelC FAILED
        TypeError: Cannot redefine property: relation
            at Object.defineProperty (<anonymous>)
            at defineProperty (test/test.jsx:6697:18)
            at ManyToMany.install (test/test.jsx:3369:38)
            at http://0.0.0.0:9876test/test.jsx:11682:39
            at http://0.0.0.0:9876test/test.jsx:7000:11
            at baseForOwn (test/test.jsx:1263:20)
            at forOwn (test/test.jsx:2703:20)
            at http://0.0.0.0:9876test/test.jsx:11680:38
            at Array.forEach (<anonymous>)
            at ORM._setupModelPrototypes (test/test.jsx:11677:16)
```

**Closed by haveyaseen** 2018-06-10 18:28 UTC
Labels: type: Bug
