### ISSUE TITLE
Model.update() does not filter out fields

### ISSUE THREAD

**Issue by pronebird** [tommikaikkonen/redux-orm#59] opened 2016-11-09 18:39 UTC
If I pass wrong payload to Model.update() it simply saves it to the store without any checks. It gets worse if model has the same method used to calculate something dynamically, then the value overlaps the function.

Consider:

```js
class Foo extends ValidatingModel {
    mutualBars() {
       return ...
    }
}
```

Then what I do essentially is, I get the ref, call `mutualBars()` and assign it to plain dummy before mapping it to React.

```js
const object = Object.assign({}, foo.ref);

// for user interface to consume/display
object.mutualBars = foo.mutualBars();
```

This is both related to redux-orm and redux-orm-proptypes. 

Prop-types could do type checking over specified fields and redux-orm could provide a way to define fields that aren't relationships. 

It feels like we should have a way to specify fields and only save relevant data. This both should prevent any trash from leaking into the state.

**Comment by tommikaikkonen** [comment] 2016-11-09 19:01
I agree, redux-orm knowing the non-relationship field names you're using would make it able to throw some helpful errors. It would be a breaking change as all models need to declare the possible fields the model could use, though.

I think the value overlapping equally named methods works as intended; property access to the Model instance values should be priority.

**Comment by pronebird** [comment] 2016-11-09 19:11
What do you think would be the best way to achieve that? Can we reuse existing `Model.fields` to declare fields on model?

**Comment by tommikaikkonen** [comment] 2016-11-09 19:30
I think having all the field information in `Model.fields` is by far the cleanest API, but that means a breaking change as Models that declare only their relationship fields will be interpreted as Models with only those fields. A backward compatible route would be to have a separate `Model.fields` property with a different name, but that's ugly.

For the `Model.fields` values for non-relationship fields, even though I'd be interested in only recording the names of the fields, it would probably be best to go for a simple `ValueField` that would subclass from `redux-orm.fields.Field` to accommodate possible future features and user extensions that handle validation etc.

```javascript
class MyModel extends Model {
  static fields = {
    relatedThing: fk('Thing'),
    someValue: value({ /* chance to pass arbitrary metadata */}),
  }
}
```

**Comment by pronebird** [comment] 2016-11-09 19:56
That sounds awesome! I think that's the way to go here. We could circumvent breaking change by checking if model has any other fields but relationship ones and simply avoid any extra steps in that case. Not sure how easy that would be but something tells me it would be a single IF and deprecation notice.

**Comment by pronebird** [comment] 2016-11-10 17:56
My attempt to add attributes declaration: https://github.com/pronebird/redux-orm/commit/949f98ce7555a7fb55f3d6a00b1e4ed4f99d06c2

Not ready to send PR, I need somebody to look at it.

Model tests fail because Schema adds properties dynamically when session calls `getModelClasses` for both relationships and attributes, but Model tests create models directly. Therefore some piece of puzzle is missing.

**Comment by tommikaikkonen** [comment] 2016-11-12 22:48
Having skimmed that commit, I think the basic idea looks good! Please open up a PR. I can have a look at the failing tests.

**Comment by pronebird** [comment] 2016-11-12 22:50
@tommikaikkonen awesome! Please take a look at #61

**Comment by haveyaseen** [comment] 2018-06-06 21:21
Closing as #62 has been merged. Also see #204 for the case of preventing updates using custom field comparisons.

**Closed by haveyaseen** 2018-06-06 21:21 UTC
